### ISSUE TITLE
question about mask magnification

### ISSUE THREAD

**Issue by NotF404** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#1]
Hi

When I check the mask of _'TCGA-34-2605-01A-01-TS1.570bb46f-3dbb-480b-adb2-b563b16e4854.svs'_, I found that the mask shape: 
`mask_path = os.path.join(mask_root, fn+'.png')
mask_224 = cv2.imread(mask_path)/255`
got results:
(72, 41, 3)

Tile counts that the openslide deepzoom shows:
![image](https://user-images.githubusercontent.com/44365487/95656108-9de76e80-0b3e-11eb-9c91-ba178b5d40ce.png)

this is the properties:
 <_PropertyMap {'aperio.AppMag': '20', 'aperio.DSR ID': '10.55.211.32', 'aperio.Date': '12/11/09', 'aperio.Filename': '12290', 'aperio.Focus Offset': '0.000000', 'aperio.ICC Profile': 'ScanScope v1', 'aperio.ImageID': '12290', 'aperio.Left': '38.545719', 'aperio.LineAreaXOffset': '0.021368', 'aperio.LineAreaYOffset': '-0.005374', 'aperio.LineCameraSkew': '-0.000389', 'aperio.MPP': '0.5015', 'aperio.OriginalWidth': '18360', 'aperio.Originalheight': '31996', 'aperio.ScanScope ID': 'SS1302', 'aperio.StripeWidth': '2040', 'aperio.Time': '16:40:54', 'aperio.Top': '19.720402', 'aperio.User': 'b1066340-e113-4e11-a4d5-4667f9fff0e7', 'openslide.comment': 'Aperio Image Library v10.0.50\r\n18360x31996 [0,100 18000x31896] (256x256) JPEG/RGB Q=70|AppMag = 20|StripeWidth = 2040|ScanScope ID = SS1302|Filename = 12290|Date = 12/11/09|Time = 16:40:54|User = b1066340-e113-4e11-a4d5-4667f9fff0e7|MPP = 0.5015|Left = 38.545719|Top = 19.720402|LineCameraSkew = -0.000389|LineAreaXOffset = 0.021368|LineAreaYOffset = -0.005374|Focus Offset = 0.000000|DSR ID = 10.55.211.32|ImageID = 12290|OriginalWidth = 18360|Originalheight = 31996|ICC Profile = ScanScope v1', 'openslide.level-count': '3', 'openslide.level[0].downsample': '1', 'openslide.level[0].height': '31896', 'openslide.level[0].tile-height': '256', 'openslide.level[0].tile-width': '256', 'openslide.level[0].width': '18000', 'openslide.level[1].downsample': '4', 'openslide.level[1].height': '7974', 'openslide.level[1].tile-height': '256', 'openslide.level[1].tile-width': '256', 'openslide.level[1].width': '4500', 'openslide.level[2].downsample': '16.00200702458605', 'openslide.level[2].height': '1993', 'openslide.level[2].tile-height': '256', 'openslide.level[2].tile-width': '256', 'openslide.level[2].width': '1125', 'openslide.mpp-x': '0.50149999999999995', 'openslide.mpp-y': '0.50149999999999995', 'openslide.objective-power': '20', 'openslide.quickhash-1': '41db6c8e68e0db6a9bc4457379d213057c57ceaa53fd341fd5537c1f12ba9014', 'openslide.vendor': 'aperio', 'tiff.ImageDescription': 'Aperio Image Library v10.0.50\r\n18360x31996 [0,100 18000x31896] (256x256) JPEG/RGB Q=70|AppMag = 20|StripeWidth = 2040|ScanScope ID = SS1302|Filename = 12290|Date = 12/11/09|Time = 16:40:54|User = b1066340-e113-4e11-a4d5-4667f9fff0e7|MPP = 0.5015|Left = 38.545719|Top = 19.720402|LineCameraSkew = -0.000389|LineAreaXOffset = 0.021368|LineAreaYOffset = -0.005374|Focus Offset = 0.000000|DSR ID = 10.55.211.32|ImageID = 12290|OriginalWidth = 18360|Originalheight = 31996|ICC Profile = ScanScope v1', 'tiff.ResolutionUnit': 'inch'}>
  
My question is that the tile shape should be (81, 143) since the slide's magnification is 20, but the mask 's shape is (72,41) which should be count as 10X. Is that right?

Best

**Comment by NotF404** [comment]
But what confused  me is that it's said that the magnification is 20X. @MarvinLer

**Comment by MarvinLer** [comment]
Hi,
Thanks for pointing this issue.
You are right, given the shape of the resulting segmentation map, this corresponds to 10x and not 20x at it should be. Did you find other slides in this case?
I will look into it this week and push a fix asap in both code and segmentation maps.

Also, we should produce more precise segmentation maps soon: with precision of 16micrometer instead of the current 112microm.

Best,
ML

**Comment by NotF404** [comment]
Hi MarvinLer

      Sorry for late replay. Actually, all the mask in results corresponds to 10x. And, thanks for you excellent work that is really helpful.
