### ISSUE TITLE
Preprocessing without downloading

### ISSUE THREAD

**Issue by dgonzMD** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#4]
Hi Marvin,

Excellent job. This is a fantastic repo and your paper is remarkable. Is there a way to skip the download step and perform preprocessing on an existing directory of WSI? Thanks!

**Comment by MarvinLer** [comment]
Hi Daniel,
Thank you very much for the kind words!
After a bit of refactoring, the latest version of the code now handles pre-processing of an existing directory of WSI without performing the download step. Also, the pre-processing script [code/data_processing/main.py](https://github.com/MarvinLer/tcga_segmentation/blob/master/code/data_processing/main.py) has now a more robust command line interface.

To use this new pre-processing regime, if you already have a folder `input_folder` containing whole slide images (or a folder containing folders each containing WSI), you can perform pre-processing with:
`python -m code.data_processing.main output_folder --no-download --source-slides-folder input_folder`
which will tile all WSI, remove background tiles and move the remaining tiles into `output_folder/filtered_tiles`

If you want to perform this along with prior download of TCGA data using a manifest file `manifest`, you can use:
`python -m code.data_processing.main output_folder --gdc-executable path_of_gdc_client --manifest manifest`

Both these regimes are compatible with the training script and can even be called using `python -m code.training` with the desired prior arguments.

Does it suit your needs?
More improvements of the data processing module incoming, such as adding magnification, tile width and other control parameters as command line arguments, and also performing tiling of only the specified magnification for quicker data pre-processing.

Best,
ML
