### ISSUE TITLE
About bag_size

### ISSUE THREAD

**Issue by riznk** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#5]
Hi, I have question regarding max_bag_size. If it is 100, does it mean we are only selecting 100 tiles/patches from each slide? or does it mean all the tiles from are divided into bags of tiles i.e. we have multiple bags from a single slide...

**Comment by MarvinLer** [comment]
Hi, this is actually the former: for each epoch, each slide is sampled once; upon sampling, `max_bag_size` (100 in your case) tiles are randomly sampled from each slide.
In other words, the number of timesteps per epoch is the number of slides of the dataset divided by the batch size, and the number of sampled tiles in total per epoch is `max_bag_size` times the number of slides.
Also for clarity, no tiles are discarded from the total pool of tiles of your dataset: the sampling of `max_bag_size` tiles from each slide is performed randomly at each timestep.

Is it clear enough?

**Comment by riznk** [comment]
Hi Marvin,
Thank you for the quick reply. yes ,it is clear now regarding bags. But, I have some questions regarding prediction(inference part). How to get the probability vectors for e.g like in your paper(fig1)? I tried to get those values(instances_predictions), but I am getting negative values, for e.g [-0.7453],
         [ 0.1658],
         [-6.1213],
         [ 1.8079],
         [ 1.0292],
         [-5.2677],
         [-3.5629],
         [ 1.8513],
         [ 0.8251],
         [ 2.1662],
         [-1.5487],
         [-5.8287],
         [ 0.1153]

**Comment by MarvinLer** [comment]
Indeed, these are just pre-activated outputs: you would need to call `torch.sigmoid` on these to get probabilities

Hope this helps
ML

**Comment by riznk** [comment]
yes , I got the results, it worked. Thank you so much for helping.

**Comment by MarvinLer** [comment]
np :)
