### ISSUE TITLE
About normalization values and segmented tumor maps

### ISSUE THREAD

**Issue by riznk** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#6]
Hi Marvin,

I wanted to know how you calculated the normalization_channels_mean and std. Also, I will be grateful if you can tell me the steps or hints to get the tumor maps for WSIs as yours. I am a bit new to histopathology image analysis and currently doing by learning.

**Comment by MarvinLer** [comment]
Hi,

1. normalization values were computed on the TCGA dataset we used in [our paper](https://arxiv.org/abs/2004.05024), which are all (training) snap-frozen slides of lung, breast and kidney. Specifically, we looped through all patches of all training slides and computed channelwise means and stds such that both R, G and B channels are of mean 0 and std 1 (before any data augmentation).
2. yes so you would need additional code to compute the tumor maps. Here are an illustration of the steps to produce such a map given a trained model from a WSI:
   - Tile the WSI into (non-overlapping) patches (using [code/data_processing/main.py](../blob/master/code/data_processing/main.py))
   - Loop through all patches by retrieveing both loaded images, as well as tiles x and y indexes, and compute a probability for each patch with the trained model
   - At this step you should have a vector of probabilities and a vector of associated x and y indexes
   - Compute a zero-filled matrix of appropriate size, and assign a RGB value of (_p_, 0, 255) at index x and y where __p__ is the predicted probability of tumor of a tile, and x and y are its indexes

Is this clear enough?

ML

**Comment by riznk** [comment]
Hi Marvin,

Thank you for nice explanations and hints. I am clear now. For tumor maps, I had got some hints from #1 (deepZoom)and assigned pixel value in  mask image according to p for patch co-ordinates(x,y) to get the map. I will also go through your method. Thank you so much for everything.

**Comment by MarvinLer** [comment]
Sure, no problem, good luck :)
