### ISSUE TITLE
Some questions about the input datas' format in training

### ISSUE THREAD

**Issue by lyl010221** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#8]
Hi! Recently I have tried another way, downloading a WSI directly from a website and place it into the ./data folder, to replace the gdc tools to get WSIs. But I am facing a new problem. Could you please give me a help?

Now please let me give a description about my process, which you can see whether there is some problem.
1. download a WSI `:TCGA-A6-3809-01A-01-BS1.44ed8b6b-5fcc-4274-9963-e54dc460c82e.svs` from a website
2. place it into the folder `~/tcga_segmentation/data`(the original folder)
3. run the code `python -m code.data_processing.main ./data --no-download --source-slides-folder ./data` . It can work well and generates a `./data/filtered_tiles folder`, a `./data/TCGA-A6-3809-01A-01-BS1.44ed8b6b-5fcc-4274-9963-e54dc460c82e.svs folder`,a `./data/has_been_moved_and_filtered.txt ` and a`./data/has_been_tiled_mag20.txt` , totally 4 things.
4. if I run the code in terminal`(tcga_segmentation) lyl010221@ubuntu:~/PycharmProjects/pythonProject/tcga_segmentation$  python -m code.training --preprocessed-data-folder ./data --alpha 0.1 --beta 0. --max-bag-size 100` as the Readme.md says, there is an error: `training.py: error: unrecognized arguments: --preprocessed-data-folder ./data`
5. if I run the code in terminal `python -m code.training --input-data-folder ./data --alpha 0.1 --beta 0. --max-bag-size 100` according to the `python -m code.training --help`'s existing parameter , there is an error:`ValueError: Download from TCGA is on: need both --gdc-executable and --manifest arguments filled`

So,my questions are below:
1. Is the code I run in my terminal correct? 
2. What is the input data's format should be for the training?
A original .svs, a folder named filtered_tiles, a folder named after the .svs  or the parent folder  named `./data`  including all the things listed above?
3. Is it a WSI too few to train?(I just want to run the model correctly so I just place a WSI  as a test, but I don't know whether more WSIs are requested)

Thank you very much for your help!

**Comment by manigalati** [comment]
Hello @lyl010221 :)

**Comment by manigalati** [comment]
Hello @lyl010221 :)

**Comment by manigalati** [comment]
Hello @lyl010221 :)

**Comment by manigalati** [comment]
Hello @lyl010221 :)

I am not the author, but maybe I can help you. Among the parameters, you should specify --source-slides-folder instead of --preprocessed-data-folder (since there is no parameter called preprocessed-data-folder in the code anymore) and --no-download in order to avoid running the preprocessing again. Indeed, as you explained in your point 3, you have already successfully run the preprocessing, and you do not need to run that again (which is what happens in training.py if you do not specify the correct parameters).

In the meanwhile, can I ask you instead how you managed to download WSI data? I would like to know which website you are referring to, since  https://portal.gdc.cancer.gov/projects seems to be down.

**Comment by lyl010221** [comment]
Hi!Thank you for your help!

But I seem to meet a new error when I run the code below :
`(tcga_segmentation) lyl010221@ubuntu:~/PycharmProjects/pythonProject/tcga_segmentation$ python -m code.training --source-slides-folder ./data --alpha 0.1 --beta 0. --max-bag-size 100 --no-download
`

And the error message is:

```
....(some unrelated INFO is ignored by me)

INFO     Initializing model... 

INFO       resnet18 architecture initialized

INFO       mil wrapper initialized

INFO     done

INFO     Pre-loading all data...

  0%|                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]

Traceback (most recent call last):

  File "/home/lyl010221/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/home/lyl010221/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)

  File "/home/lyl010221/PycharmProjects/pythonProject/tcga_segmentation/code/training.py", line 343, in <module>
    main(define_args())

  File "/home/lyl010221/PycharmProjects/pythonProject/tcga_segmentation/code/training.py", line 282, in main
    train_dataset, val_dataset, test_dataset = build_datasets(source_slides_folders=slides_folders,

  File "/home/lyl010221/PycharmProjects/pythonProject/tcga_segmentation/code/training.py", line 140, in build_datasets
    whole_dataset = Dataset(slides_folders=source_slides_folders, model_input_size=model_input_width,

  File "/home/lyl010221/PycharmProjects/pythonProject/tcga_segmentation/code/data_processing/pytorch_dataset.py", line 61, 
in __init__
    slides_ids, slides_labels, slides_summaries, slides_cases, slides_images_filepaths = self.load_data()

  File "/home/lyl010221/PycharmProjects/pythonProject/tcga_segmentation/code/data_processing/pytorch_dataset.py", line 99, in load_data
    all_slide_files = list(filter(lambda f: os.path.isfile(os.path.join(slide_folder, f)),

  File "/home/lyl010221/PycharmProjects/pythonProject/tcga_segmentation/code/data_processing/pytorch_dataset.py", line 99, in <lambda>
    all_slide_files = list(filter(lambda f: os.path.isfile(os.path.join(slide_folder, f)),

  File "/home/lyl010221/anaconda3/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)

  File "/home/lyl010221/anaconda3/lib/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: Can't mix strings and bytes in path components
```
I try to find the solution of it in the website, but it doesn't seem to fit my problem well. Could you please help with it? Thank you!
PS:I don't know whether the number of WSI will  be influential (Now I use only one WSI)

**Comment by MarvinLer** [comment]
Hi,
Yes this is the correct process to use custom slides @manigalati, thank you for the help!

@lyl010221 this bug comes from the fact that somehow some paths are strings while others are bytes. 
You can fix it by changing the following lines 99-100 in the file [code/data_processing/pytorch_dataset.py](../tree/master/code/data_processing/pytorch_dataset.py#L99):
```
all_slide_files = list(filter(lambda f: os.path.isfile(os.path.join(slide_folder, f)),
                              os.listdir(slide_folder)))
```

to
```
all_slide_files = list(filter(lambda f: os.path.isfile(os.path.join(slide_folder, f)),
                              list(map(lambda f: f.decode("utf-8"), os.listdir(slide_folder)))))
```
which converts all tiles paths to the correct format.

ML

**Comment by lyl010221** [comment]
> Hi,
> Yes this is the correct process to use custom slides @manigalati, thank you for the help!
> 
> @lyl010221 this bug comes from the fact that somehow some paths are strings while others are bytes.
> You can fix it by changing the following lines 99-100 in the file [code/data_processing/pytorch_dataset.py](../tree/master/code/data_processing/pytorch_dataset.py#L99):
> 
> ```
> all_slide_files = list(filter(lambda f: os.path.isfile(os.path.join(slide_folder, f)),
>                               os.listdir(slide_folder)))
> ```
> 
> to
> 
> ```
> all_slide_files = list(filter(lambda f: os.path.isfile(os.path.join(slide_folder, f)),
>                               list(map(lambda f: f.decode("utf-8"), os.listdir(slide_folder)))))
> ```
> 
> which converts all tiles paths to the correct format.
> 
> ML

ok,Thank you very much!
