### ISSUE TITLE
Question regarding the data shape

### ISSUE THREAD

**Issue by manigalati** [MarvinLer/tcga_weakly_MIL_WSI_segmentation#9]
Hello :)
I have a question regarding the dimensions of the data loaded at each epoch from the dataloader. Since the GDC Data Portal seems to be down, I cannot download any data to run an example. My only option is to run your code by plugging my data. However, I don't know the shape each batch of data has at each epoch. My guess is that the shape of the images is 1xBx3xWxH, where B is the max bag size you can set as parameter. Instead, the shape of the label is 1, meaning that all the slides loaded at one epoch has to belong to the same class. Are my assumptions correct?

Thank you in advance :)

Francesco

**Comment by MarvinLer** [comment]
Hi,
Sorry for the late reply, not sure if you figured this out yet

The shape of the images is indeed 1xBx3xWxH with B equal to the --max-bag-size parameter, i.e. the number of tiles sampled per WSI. E.g. a shape `[1, 100, 3, 224, 224]`.
The shape of the label is indeed `[1]`.

Is it okay for you? Did you manage to use it with your own data?

Best,
ML
